mission:
  target:          Jupiter
  allowed_bodies:  [Mercury, Venus, Earth, Mars]
  max_flybys:      8
  min_flybys:      2
  tof_bounds:      [25, 1200.0]      # each leg [d]
  t0_window:       [0.0, 1926.0]       # launch window [d]
  penalty_weights:
    time:          1.0
    perigee:       10.0

chromosome:
  real_bounds:     # real-valued genes (e.g. leg times, φ angles)
    - [0.0, 1826.0]   # gene 3: leg-1 time of flight [d]
    - [25.0, 1500.0]   # gene 4: leg-2 time of flight
    - [0.0, 360.0]   # gene 5: φ angle 1 [deg]
    - [0.0, 360.0]   # gene 6: φ angle 2

ga:
  pop_size:        200
  generations:     20
  elite:           8
  cx_prob:         0.9
  int_mut_prob:    0.10
  real_mut_prob:   0.10
  tournament_k:    3
  seed:            42